version: '3.9'
services:
  oauth2_proxy:
    # image: quay.io/oauth2-proxy/oauth2-proxy
    image: oauth2-proxy
    build:
      context: .
    # ports:
    #   - 4180:4180
    expose:
      - 4180
    command:
      - --upstream=http://localhost:3300/
      - --provider=oidc
      # - --login-url=http://hydra:4444/oauth2/auth?response_type=code&client_id=members_application&scope=openid+members&redirect_uri=http%3A%2F%member%3A4180%2Foauth2%2Fcallback&state=ZGHWfNTjeY
      # - --oidc-issuer-url=http://hydra:4444/
      # - --oidc-jwks-url=http://hydra:4455/.well-known/jwks.json
      - --login-url=http://localhost:4444/oauth2/auth?response_type=code&client_id=members_application&scope=openid+members&redirect_uri=http%3A%2F%member%3A4180%2Foauth2%2Fcallback&state=ZGHWfNTjeY
      - --oidc-issuer-url=http://localhost:4444/
      - --oidc-jwks-url=http://localhost:4455/.well-known/jwks.json
      - --redirect-url=http://member:4180/oauth2/callback
      - --client-id=members_application
      - --client-secret=secret
      - --email-domain=*
      - --cookie-secret=hu9XrailLtAYwQCHyQkGUw==
      - --cookie-secure=false
      # for debug
      - --show-debug-on-error=true
      # - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
    # networks:
      # - oidc_network
    network_mode: host
# networks:
#   oidc_network:
#     external: true
#     name: hydra_intranet
