version: '3.1'
services:
  oathkeeper:
    image: oryd/oathkeeper:v0.38.9-alpine
    ports:
    - 80:4455
    # - 4456:4456
    volumes:
    - type: bind
      source: ./.oathkeeper.yaml
      target: /home/ory/.oathkeeper.yaml
    - type: bind
      source: ./access_rules.yaml
      target: /home/ory/access_rules.yaml
